### ISSUE TITLE
zstd decompression

### ISSUE THREAD

**Issue by Zer0-One** [robinlinden/hastur#956]
Needed for `Content-Encoding: zstd`

https://datatracker.ietf.org/doc/html/rfc8878

**Comment by Zer0-One** [comment]
Too late to beat Chromium, but we can beat Mozilla to the punch if we implement this first.

**Comment by robinlinden** [comment]
Since zstd has support for generating dictionaries from a corpus, I guess looking at generating a dictionary at build-time from something like the wpt test data we already use might be a neat option.

If we're generating a dictionary instead of pulling it from another repo, we'll want to check that the generated dictionary is reproducible as well.

**Comment by robinlinden** [comment]
Done in #973, #980
